# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: npm package

on:
    release:
        types: [created]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
    publish-npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV
            - uses: pnpm/action-setup@v4
              with:
                version: ${{ fromJson(env.PACKAGE_JSON).volta.pnpm }}
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ fromJson(env.PACKAGE_JSON).volta.node }}
                registry-url: https://registry.npmjs.org/
            - run: pnpm install --frozen-lockfile
            - run: pnpm clean
            - run: pnpm build
            - run: pnpm -r publish --no-git-checks --access public
